server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    keep-alive-timeout: 100
    threads:
      max: 200
      min-spare: 10
    accept-count: 100

spring:
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
